version: '3'
services:

  app:
    image: jwilder/whoami
    env_file: .env
    restart: ${RESTART}
    environment:
      - LETSENCRYPT_HOST=${MYHOST}
      - VIRTUAL_HOST=${MYHOST}
      - VIRTUAL_PATH=/${DOMAIN_PATH}/whoami
    networks:
      - topDomainProxy

  cache:
    image: redis:6.2.6
    networks:
      - custom_network

# Redundant, but needed for scaling. Check x-common-params: &common-params to reduce redundancy

  directus-master:
#    container_name: directusWithCache${DOMAIN_PATH} # Cant use container name due to scaling
    build:
      context: ./
    env_file: .env
    expose:
      - ${BACKEND_PORT}
    restart: ${RESTART}
    depends_on:
      - cache
    volumes:
      # By default, uploads are stored in /directus/uploads
      # Always make sure your volumes matches the storage root when using
      # local driver
      - ./Backend/uploads:/directus/uploads
      # Make sure to also mount the volume when using SQLite
      - ./Backend/database:/directus/database
      # If you want to load extensions from the host
      - ./Backend/directusExtensions:/directus/extensions
      # directus-auto-translation api key path
      - ./Backend/secrets:/directus/secrets
    networks:
      - directus
      - custom_network
      - topDomainProxy
    environment:
      INSTANCE_ID: "master"
      LETSENCRYPT_HOST: ${MYHOST}
      VIRTUAL_HOST: ${MYHOST}
      VIRTUAL_PATH: /${DOMAIN_PATH}/${BACKEND_PATH}/
      VIRTUAL_DEST: /
      VIRTUAL_PORT: ${BACKEND_PORT}

      HOST: "0.0.0.0"
      PUBLIC_URL: ${DOMAIN_PRE}://${MYHOST}/${DOMAIN_PATH}/${BACKEND_PATH}

      KEY: '255d861b-5ea1-5996-9aa3-922530ec40b1'
      SECRET: '6116487b-cda1-52c2-b5b5-c8022c45e263'

      DB_CLIENT: 'sqlite3' # https://docs.directus.io/configuration/config-options/
      DB_FILENAME: './database/data.db'
      #DB_HOST: 'database' #Required when using pg, mysql, oracledb, or mssql
      #DB_PORT: '5432'
      #DB_DATABASE: 'directus'
      #DB_USER: 'directus'
      #DB_PASSWORD: 'directus'

      TZ: "Europe/Berlin"

      CACHE_ENABLED: "true"
      CACHE_STORE: "redis"
      REDIS: "redis://cache:6379"
      CACHE_AUTO_PURGE: 'true'

      ADMIN_EMAIL: 'admin@example.com'
      ADMIN_PASSWORD: 'd1r3ctu5'

#      EMAIL_FROM: "no-reply@nilsbaumgartner.de"
#      EMAIL_TRANSPORT: "smtp"
#      EMAIL_SMTP_HOST: "smtp.strato.de"
#      EMAIL_SMTP_PORT: "587"
#      EMAIL_SMTP_USER: "no-reply@nilsbaumgartner.de"
#      EMAIL_SMTP_PASSWORD: "${MAIL_PASSWORD}"
#      EMAIL_SMTP_POOL: ""
#      EMAIL_SMTP_SECURE: "true"
#      EMAIL_SMTP_IGNORE_TLS: "true"

      CORS_ENABLED: "true"
      CORS_ORIGIN: "true"
      REFRESH_TOKEN_COOKIE_SAME_SITE: "lax"
      #CORS_ALLOWED_HEADERS: 'Access-Control-Allow-Origin,Authorization,Accept,Accept-Encoding,Accept-Language,Access-Control-Request-Headers,Access-Control-Request-Method,Cache-Control,Connection,Content-Type,Host,Origin,Pragma,Referer,Sec-Fetch-Mode,User-Agent'
      #CORS_EXPOSED_HEADERS: 'Access-Control-Allow-Origin,Authorization,Accept,Accept-Encoding,Accept-Language,Access-Control-Request-Headers,Access-Control-Request-Method, Cache-Control,Connection,Content-Type,Host,Origin,Pragma,Referer,Sec-Fetch-Mode,User-Agent'

      AUTH_PROVIDERS: "${AUTH_PROVIDERS}"

      AUTH_APPLE_DRIVER: "openid"
      AUTH_APPLE_CLIENT_ID: "${AUTH_APPLE_CLIENT_ID}"
      AUTH_APPLE_CLIENT_SECRET: "${AUTH_APPLE_CLIENT_SECRET}"
      AUTH_APPLE_DEFAULT_ROLE_ID: "${DEFAULT_ROLE_ID}" #If you want to set a default role id
      AUTH_APPLE_SCOPE: "openid"
      AUTH_APPLE_IDENTIFIER_KEY: "sub"
      AUTH_APPLE_ALLOW_PUBLIC_REGISTRATION: "true"
      AUTH_APPLE_ISSUER_URL: "https://appleid.apple.com/.well-known/openid-configuration"
      AUTH_APPLE_ICON: "apple"

      AUTH_GOOGLE_DRIVER: "openid"
      AUTH_GOOGLE_CLIENT_ID: "${AUTH_GOOGLE_CLIENT_ID}"
      AUTH_GOOGLE_CLIENT_SECRET: "${AUTH_GOOGLE_CLIENT_SECRET}"
      AUTH_GOOGLE_ISSUER_URL: "https://accounts.google.com"
      AUTH_GOOGLE_IDENTIFIER_KEY: "email"
      AUTH_GOOGLE_ICON: "google"
      AUTH_GOOGLE_LABEL: "Google"
      AUTH_GOOGLE_ALLOW_PUBLIC_REGISTRATION: "true"
      AUTH_GOOGLE_DEFAULT_ROLE_ID: "${DEFAULT_ROLE_ID}"


      NODE_TLS_REJECT_UNAUTHORIZED: 0 # The HTTPS cert is not complete: "unable to verify the first certificate"

      ACCESS_TOKEN_TTL: "15m"
      REFRESH_TOKEN_TTL: "180d"

      MAX_PAYLOAD_SIZE: "80mb"


      # directus-auto-translation
      AUTO_TRANSLATE_API_KEY_SAVING_PATH: "/directus/secrets/auto-translation-api-key.txt"

networks:
  custom_network: {}
  directus:
  topDomainProxy:
    external: true
