version: '3.8'

services:
  rocket-meals-cache:
    image: redis:6.2.6
    networks:
      - directus_network

  rocket-meals-directus:
    build:
      context: ./
    container_name: "rocket-meals-directus"
    networks:
      - traefik
      - directus_network
    labels:
      traefik.enable: "true"
      traefik.http.routers.directus-api.entrypoints: websecure
      traefik.http.routers.directus-api.rule: Host(`127.0.0.1`) && PathPrefix(`/rocket-meals/api`)
      traefik.http.routers.directus-api.tls: "true"
      traefik.http.routers.directus-api.tls.certresolver: tls
      traefik.http.services.directus-api.loadbalancer.server.port: 8055
      traefik.http.middlewares.directus-api-stripprefix.stripprefix.prefixes: /rocket-meals/api
      traefik.http.routers.directus-api.middlewares: directus-api-stripprefix
      # network: traefik
      traefik.docker.network: traefik
    environment:
      # Traefik configuration
      PUBLIC_URL: "https://127.0.0.1/rocket-meals/api"
      ROOT_REDIRECT: "./api/admin"
      # Directus configuration
      ADMIN_EMAIL: "admin@example.com"
      ADMIN_PASSWORD: "d1r3ctu5"

networks:
  directus_network: {}
  traefik:
    external: true
    name: traefik
