services:
  rocket-meals-backend:
    image: "jwilder/whoami"
    container_name: "rocket-meals-backend"
    env_file:
      - ".env"
    networks:
      - traefik
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=traefik"
      - "traefik.http.middlewares.https-redirect.redirectscheme.scheme=https"
      - "traefik.http.middlewares.strip-backend.stripPrefix.prefixes=/backend"

      - "traefik.http.routers.rocket-meals-backend.entrypoints=web"
      - "traefik.http.routers.rocket-meals-backend.rule=Host(`${MYHOST}`) && PathPrefix(`/backend/ping`)"
      - "traefik.http.routers.rocket-meals-backend.middlewares=https-redirect"

      - "traefik.http.routers.rocket-meals-backend-secure.entrypoints=websecure"
      - "traefik.http.routers.rocket-meals-backend-secure.rule=Host(`${MYHOST}`) && PathPrefix(`/backend/ping`)"
      - "traefik.http.routers.rocket-meals-backend-secure.middlewares=strip-backend"
      - "traefik.http.routers.rocket-meals-backend-secure.tls=true"
      - "traefik.http.routers.rocket-meals-backend-secure.tls.certresolver=${RESOLVER}"


networks:
  traefik:
    external: true
    name: traefik