version: "3.3"

services:
  rocket-meals-service:
    image: "traefik/whoami"
    container_name: "rocket-meals-service"
    networks:
      - traefik
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.rocket-meals-service.rule=PathPrefix(`/rocket-meals/ping`)"
      - "traefik.http.middlewares.strip-rocket-meals.stripPrefix.prefixes=/rocket-meals"
      - "traefik.http.routers.rocket-meals-service.middlewares=strip-rocket-meals"
      - "traefik.http.routers.rocket-meals-service.entrypoints=websecure"
      - "traefik.http.routers.rocket-meals-service.tls.certresolver=myresolver"

networks:
  traefik:
    external:
      name: traefik
