version: '3.8'

services:
  rocket-meals-cache:
    image: redis:6.2.6
    networks:
      - directus_network

  rocket-meals-directus:
    build:
      context: ./
    container_name: "rocket-meals-directus"
    networks:
      - traefik
      - directus_network
    labels:
      traefik.enable: "true"
      traefik.http.routers.directus.entrypoints: websecure
      traefik.http.routers.directus.rule: Host(`${MYHOST}`) && PathPrefix(`/${ROCKET_MEALS_PATH}/${ROCKET_MEALS_BACKEND_PATH}`)
      traefik.http.routers.directus.tls: "true"
      traefik.http.routers.directus.tls.certresolver: tls
      traefik.http.services.directus.loadbalancer.server.port: 8055
      traefik.http.middlewares.directus-stripprefix.stripprefix.prefixes: /${ROCKET_MEALS_PATH}/${ROCKET_MEALS_BACKEND_PATH}
      traefik.http.routers.directus.middlewares: directus-stripprefix
      # network: traefik
      traefik.docker.network: traefik
    environment:
      # Traefik configuration
      PUBLIC_URL: "https://${MYHOST}/${ROCKET_MEALS_PATH}/${ROCKET_MEALS_BACKEND_PATH}"
      ROOT_REDIRECT: "./${ROCKET_MEALS_BACKEND_PATH}/admin"
      # Directus configuration
      ADMIN_EMAIL: "admin@example.com"
      ADMIN_PASSWORD: "d1r3ctu5"

networks:
  directus_network: {}
  traefik:
    external: true
    name: traefik
