#!/usr/bin/env python3
"""
Generate TTS voice MP3 files from a JSON definition file using Voxtral (Mistral AI).

Requires the MISTRAL_API_KEY environment variable to be set.
Designed for GitHub Actions CI.

Usage:
    python scripts/generate-tts-voices.py

Reads:  apps/geonexia/frontend/assets/tts-generated-voices/voices.json
Writes: apps/geonexia/frontend/assets/tts-generated-voices/<key>.mp3
        apps/geonexia/frontend/assets/tts-generated-voices/generatedVoicesIndex.ts
"""

import base64
import json
import os
import sys
from pathlib import Path

from mistralai import Mistral

# ── Paths ──────────────────────────────────────────────────────────────────────

REPO_ROOT = Path(__file__).resolve().parent.parent
VOICES_DIR = REPO_ROOT / "apps" / "geonexia" / "frontend" / "assets" / "tts-generated-voices"
VOICES_JSON = VOICES_DIR / "voices.json"
GENERATED_INDEX = VOICES_DIR / "generatedVoicesIndex.ts"

# ── Voxtral model ─────────────────────────────────────────────────────────────

VOXTRAL_MODEL = "voxtral-mini-tts-2603"


def detect_language(key: str) -> str:
    """Extract language code from the key prefix (e.g. 'DE' from 'DE_de_...')."""
    return key.split("_")[0].upper()


def generate_mp3(client: Mistral, text: str, output_path: Path) -> bool:
    """Generate an MP3 file from text using the Voxtral TTS API."""
    try:
        response = client.audio.speech.complete(
            model=VOXTRAL_MODEL,
            input=text,
            response_format="mp3",
            stream=False,
        )
        audio_bytes = base64.b64decode(response.audio_data)
        output_path.write_bytes(audio_bytes)
        return True
    except Exception as exc:
        print(f"  [ERROR] Voxtral API call failed: {exc}")
        return False


def generate_typescript_index(voices: dict[str, str]) -> None:
    """Generate the TypeScript index file with static require() mappings."""
    lines = [
        "// Auto-generated by scripts/generate-tts-voices.py",
        "// Do not edit manually – re-run the generate-tts-voices workflow instead.",
        "",
        "export type GeneratedVoiceEntry = {",
        "\ttext: string;",
        "\taudio: number; // Metro require() asset ID",
        "};",
        "",
        "export const generatedVoices: Record<string, GeneratedVoiceEntry> = {",
    ]

    for key, text in voices.items():
        escaped_text = text.replace("\\", "\\\\").replace("'", "\\'")
        lines.append(f"\t'{key}': {{")
        lines.append(f"\t\ttext: '{escaped_text}',")
        # eslint-disable-next-line ... is added to avoid require() lint warnings
        lines.append(f"\t\t// eslint-disable-next-line @typescript-eslint/no-require-imports")
        lines.append(f"\t\taudio: require('./{key}.mp3'),")
        lines.append(f"\t}},")

    lines.append("};")
    lines.append("")

    GENERATED_INDEX.write_text("\n".join(lines), encoding="utf-8")
    print(f"Generated TypeScript index: {GENERATED_INDEX}")


def main() -> None:
    api_key = os.environ.get("MISTRAL_API_KEY")
    if not api_key:
        print("ERROR: MISTRAL_API_KEY environment variable is not set.")
        sys.exit(1)

    if not VOICES_JSON.exists():
        print(f"ERROR: voices.json not found at {VOICES_JSON}")
        sys.exit(1)

    with open(VOICES_JSON, "r", encoding="utf-8") as f:
        voices: dict[str, str] = json.load(f)

    print(f"Found {len(voices)} voice entries to generate.")
    print(f"Using model: {VOXTRAL_MODEL}")

    client = Mistral(api_key=api_key)

    success_count = 0
    fail_count = 0

    for key, text in voices.items():
        output_path = VOICES_DIR / f"{key}.mp3"
        lang = detect_language(key)

        print(f"  [{lang}] {key}")
        print(f"         \"{text}\"")

        if generate_mp3(client, text, output_path):
            print(f"         ✓ {output_path.name}")
            success_count += 1
        else:
            print(f"         ✗ FAILED")
            fail_count += 1

    # Generate TypeScript index for all entries (even if some MP3s failed,
    # the require() will simply fail at build time, making the issue visible).
    generate_typescript_index(voices)

    print(f"\nDone: {success_count} succeeded, {fail_count} failed out of {len(voices)}.")
    if fail_count > 0:
        sys.exit(1)


if __name__ == "__main__":
    main()
