#!/bin/bash
# scripts/generateCustomer.sh
# Generates apps/frontend/app/getCustomer.ts with the customer name derived
# from the current repository (GITHUB_REPOSITORY = "owner/repo").
# The generated file is gitignored so it never causes merge conflicts.

case "$GITHUB_REPOSITORY" in
  rocket-meals/swosy)
    CUSTOMER="swosy"
    ;;
  rocket-meals/studi-futter)
    CUSTOMER="studi-futter"
    ;;
  *)
    CUSTOMER="test"
    ;;
esac

OUTPUT_FILE="apps/frontend/app/getCustomer.ts"

cat > "$OUTPUT_FILE" << EOF
// This file is auto-generated by scripts/generateCustomer.sh
// Do not edit manually – it is gitignored and regenerated during CI.
export function getCustomer(): string {
	return '${CUSTOMER}';
}
EOF

echo "Generated ${OUTPUT_FILE} with customer='${CUSTOMER}'"
