name: 🤖 Expo Update

on:
  workflow_run:
    workflows: ["🔧 Auto-Linter"]
    branches: [master]
    types:
      - completed

jobs:
  update:
    name: 🏗 EAS Update Production
    runs-on: ubuntu-latest
    if: ${{ github.event_name == 'workflow_run' && github.event.workflow_run.conclusion == 'success' }}
    steps:
      - name: 🔄 Checkout Repository
        uses: actions/checkout@v3

      - name: 🧰 Setup Node.js, Yarn & Dependencies
        uses: ./.github/actions/setup-and-install
        with:
          EXPO_TOKEN: ${{ secrets.EXPO_TOKEN }}

      - name: 🚀 Publish update
        run: eas update --auto --platform all --non-interactive --channel production
        working-directory: ./apps/frontend/app
        env:
          EXPO_TOKEN: ${{ secrets.EXPO_TOKEN }}
