name: Screenshots CI Action

on:
  workflow_dispatch:
    inputs:
      start:
        description: 'Write anything to start the workflow'
        required: true
        default: ''
  workflow_run:
    workflows: ["GH-Pages Publish"]
    types:
      - completed

jobs:
  start:
    runs-on: ubuntu-latest
    steps:
      - name: Confirm Workflow Start
        run: echo "Screenshots CI Action workflow started"

  screenshots:
    runs-on: ubuntu-latest
    needs: start  # Dependent on the dummy job

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Generate Screenshots - Housing
        uses: flameddd/screenshots-ci-action@master
        with:
          url: https://${{ github.repository_owner }}.github.io/${{ github.event.repository.name }}/housing?kiosk_mode=true&deviceMock=iphone
          devices: iPhone 13 Pro Max, iPhone 8, iPad (gen 7), iPad Pro 11
          waitForSelector: "#app"
          waitForTimeout: 5000
          output_dir: screenshots

      - name: Upload Screenshots
        uses: actions/upload-artifact@v2
        with:
          path: screenshots
          name: ${{ github.event.repository.name }}-screenshots

      - name: Prevent Triggering Another Workflow
        if: github.event_name == 'workflow_run'
        run: |
          echo "Skipping CI run for screenshot upload"
          git update-index --skip-worktree screenshots/
