name: 🤖 Build & Submit Android

on:
  workflow_run:
    workflows: ["🔧 Auto-Linter"]
    branches: [master]
    types:
      - completed

jobs:
  build-android:
    name: 📦 Build & 🚀 Submit Android App
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    permissions:
      contents: write

    steps:
      - name: 🧰 Setup Expo Environment
        uses: ./.github/actions/setup-expo-environment
        with:
          EXPO_TOKEN: ${{ secrets.EXPO_TOKEN }}

      - name: 🔢 Increment Build Number
        id: increment
        uses: ./.github/actions/increment-build-number
        with:
          working-directory: apps/frontend/app
          commit-message: '🔢 Increment Android build number [skip ci]'

      - name: 🛠️ Build Android App
        run: eas build --platform android --non-interactive --profile production
        working-directory: ./apps/frontend/app
        env:
          EXPO_TOKEN: ${{ secrets.EXPO_TOKEN }}

      - name: 📤 Submit Android Build to Play Store
        run: eas submit --platform android --non-interactive --latest --profile production
        working-directory: ./apps/frontend/app
        env:
          EXPO_TOKEN: ${{ secrets.EXPO_TOKEN }}
