name: GH-Pages Publish
on:
  push:
    branches:
      - dev
      - main
      - master
    paths:
      - 'frontend/app/**'
      
jobs:
  gh-pages:
    defaults:
      run:
        working-directory: ./frontend/app
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '16.x'
          registry-url: 'https://registry.npmjs.org'
      - run: npm ci
      - run: npm install @unimodules/core@~7.2.0 --force
      - run: git config --global user.name 'Rocket Meals'
      - run: git config --global user.email 'nils@baumgartner-software.de'
      #https://www.npmjs.com/package/gh-pages
      - run: |
          git remote set-url origin https://git:${GITHUB_TOKEN}@github.com/${GITHUB_REPOSITORY}.git
          CI=false npm run deployghpages -- -u "github-actions-bot <support+actions@github.com>"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # Needed to get PR information, if any
