name: Screenshots CI Action

on:
  workflow_dispatch:
    inputs:
      start:
        description: 'Write anything to start the workflow'
        required: true
        default: ''
  workflow_run:
    workflows: ["GH-Pages Publish"]
    types:
      - completed

jobs:
  start:
    runs-on: ubuntu-latest
    steps:
      - name: Confirm Workflow Start
        run: echo "Screenshots CI Action workflow started"

  screenshots:
    runs-on: ubuntu-latest
    needs: start  # Dependent on the dummy job

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'

      - name: Create Screenshots Directory
        run: mkdir -p ${{ github.workspace }}/screenshots

      - name: Install and Build
        run: npm install && npm run build
        working-directory: tools/screenshotGenerator

      - name: Debug Environment Variables
        run: |
          echo "REPOSITORY_OWNER=${{ github.repository_owner }}"
          echo "REPOSITORY_NAME=${{ github.repository_name }}"
          echo "SCREENSHOT_DIR=${{ github.workspace }}/screenshots"

      - name: Generate Screenshots
        run: npm run start
        working-directory: tools/screenshotGenerator
        env:
          REPOSITORY_OWNER: ${{ github.repository_owner }}
          REPOSITORY_NAME: ${{ github.repository_name }}
          SCREENSHOT_DIR: ${{ github.workspace }}/screenshots

      - name: Upload Screenshots
        uses: actions/upload-artifact@v2
        with:
          path: ${{ github.workspace }}/screenshots
          name: ${{ github.event.repository.name }}-screenshots

      - name: Prevent Triggering Another Workflow
        if: github.event_name == 'workflow_run'
        run: |
          echo "Skipping CI run for screenshot upload"
          git update-index --skip-worktree screenshots/
