name: Screenshots CI Action

on:
  push:
    branches:
      - master
  pull_request:  # Trigger on pull requests to master
    branches:
      - master

jobs:
  screenshots:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Generate Screenshots
        uses: flameddd/screenshots-ci-action@master
        with:
          url: https://{{ github.repository_owner }}.github.io/${{ github.repository.split('/').pop() }}/housing?kiosk_mode=true&deviceMock=iphone
          devices: iPhone 6,iPhone 6 landscape,Nexus 7,Pad Pro,Galaxy S III landscape,iPad Pro landscape
          output_dir: screenshots

      - name: Upload Screenshots
        uses: actions/upload-artifact@v2
        with:
          path: screenshots
          name: ${{ github.repository.split('/').pop() }}-screenshots

      - name: Prevent Triggering Another Workflow
        if: github.event_name == 'push'
        run: |
          echo "Skipping CI run for screenshot upload"
          git update-index --skip-worktree screenshots/
