name: Screenshots CI Action

on:
  workflow_run:
    workflows: ["GH-Pages Publish"]
    types:
      - completed

jobs:
  start:
    runs-on: ubuntu-latest
    steps:
      - name: Confirm Workflow Start
        run: echo "Screenshots CI Action workflow started"

  screenshots:
    runs-on: ubuntu-latest
    needs: start  # Dependent on the dummy job

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Generate Screenshots
        uses: flameddd/screenshots-ci-action@master
        with:
          url: https://${{ github.repository_owner }}.github.io/${{ github.event.repository.name }}/housing?kiosk_mode=true&deviceMock=iphone
          devices: iPhone 6,iPhone 6 landscape,Nexus 7,iPad Pro,Galaxy S III landscape,iPad Pro landscape
          output_dir: screenshots

      - name: Upload Screenshots
        uses: actions/upload-artifact@v2
        with:
          path: screenshots
          name: ${{ github.event.repository.name }}-screenshots

      - name: Prevent Triggering Another Workflow
        if: github.event_name == 'workflow_run'
        run: |
          echo "Skipping CI run for screenshot upload"
          git update-index --skip-worktree screenshots/
