name: Frontend Setup and Install

on:
  workflow_dispatch:

jobs:
  setup:
    name: 🏗 Setup & Install
    runs-on: ubuntu-latest
    steps:
      - name: 🔄 Checkout repository
        uses: actions/checkout@v3

      - name: 🧩 Run shared setup
        uses: ./.github/actions/setup-and-install
