name: 🍏 Build & Submit iOS

on:
  workflow_run:
    workflows: ["🔧 Auto-Linter"]
    branches: [master]
    types:
      - completed

jobs:
  build-ios:
    name: 📦 Build & 🚀 Submit iOS App
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    permissions:
      contents: write

    steps:
      - name: 🧰 Setup Expo Environment
        uses: ./.github/actions/setup-expo-environment
        with:
          EXPO_TOKEN: ${{ secrets.EXPO_TOKEN }}

      - name: 🔢 Increment Build Number
        id: increment
        uses: ./.github/actions/increment-build-number
        with:
          working-directory: apps/frontend/app
          commit-message: '🔢 Increment iOS build number [skip ci]'

      - name: 🛠️ Build iOS App
        run: eas build --platform ios --non-interactive --profile production
        working-directory: ./apps/frontend/app
        env:
          EXPO_TOKEN: ${{ secrets.EXPO_TOKEN }}

      - name: 📤 Submit iOS Build to App Store
        run: eas submit --platform ios --non-interactive --latest --profile production
        working-directory: ./apps/frontend/app
        env:
          EXPO_TOKEN: ${{ secrets.EXPO_TOKEN }}
